version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/article_monster
      - REDIS_URL=redis://redis:6379
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - IMAP_SERVER=${IMAP_SERVER:-imap.gmail.com}
      - IMAP_PORT=${IMAP_PORT:-993}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
      - FROM_EMAIL=${FROM_EMAIL}
    depends_on:
      - db
      - redis
    volumes:
      - ./articles:/app/articles
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=article_monster
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/article_monster
      - REDIS_URL=redis://redis:6379
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - IMAP_SERVER=${IMAP_SERVER:-imap.gmail.com}
      - IMAP_PORT=${IMAP_PORT:-993}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
      - FROM_EMAIL=${FROM_EMAIL}
    depends_on:
      - db
      - redis
    volumes:
      - ./articles:/app/articles
    restart: unless-stopped

  scheduler:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/article_monster
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data: