#!/bin/bash

# Script to rename GitHub repository from article-library to article-monster

echo "🦾 GitHub Repository Rename Instructions"
echo "========================================"
echo ""
echo "To rename your GitHub repository, you have two options:"
echo ""
echo "Option 1: Using GitHub CLI (gh)"
echo "--------------------------------"
echo "If you have the GitHub CLI installed, run:"
echo ""
echo "  gh repo rename article-monster"
echo ""
echo "Option 2: Using GitHub Web Interface"
echo "------------------------------------"
echo "1. Go to your repository on GitHub"
echo "2. Click on 'Settings' tab"
echo "3. In the 'General' section, find 'Repository name'"
echo "4. Change 'article-library' to 'article-monster'"
echo "5. Click 'Rename'"
echo ""
echo "After renaming, update your local git remote:"
echo "----------------------------------------------"
echo "Run these commands after the repository is renamed:"
echo ""
echo "  git remote set-url origin https://github.com/YOUR_USERNAME/article-monster.git"
echo ""
echo "Or if using SSH:"
echo ""
echo "  git remote set-url origin git@github.com:YOUR_USERNAME/article-monster.git"
echo ""
echo "To verify the change:"
echo ""
echo "  git remote -v"
echo ""