name: Rebase Debug Branch on Main Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  rebase-debug-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Rebase debug branch
        run: |
          # Check if latest-outputs-debug branch exists
          if git show-ref --verify --quiet refs/remotes/origin/latest-outputs-debug; then
            echo "Debug branch exists, rebasing..."
            
            # Fetch and checkout the debug branch
            git fetch origin latest-outputs-debug
            git checkout latest-outputs-debug
            
            # Rebase onto main
            # Since outputs/ folder only exists on debug branch, no conflicts expected
            git rebase main || {
              echo "Rebase failed - manual intervention required"
              echo "The latest-outputs-debug branch could not be automatically rebased."
              echo "Please manually rebase or reset the branch."
              exit 1
            }
            
            # Force push the rebased branch
            git push origin latest-outputs-debug --force
            echo "Successfully rebased latest-outputs-debug onto main"
          else
            echo "WARNING: latest-outputs-debug branch does not exist!"
            echo "The debug system requires this branch to be created manually."
            echo "To create it, run:"
            echo "  git checkout -b latest-outputs-debug"
            echo "  git push origin latest-outputs-debug"
            echo "Skipping rebase - no debug branch to rebase."
          fi